import Hero from "@/components/marketing/features/hero";
import { FallInPlace } from "@/components/motion/fall-in-place";
import { Br } from "@/components/typography";
import { Box, Stack } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        as={Stack}
        id="home"
        alignItems="center"
        textAlign="center"
        title={
          <FallInPlace textAlign="center" initialInView>
            Codyman의 웹 개발 저장소를 공유합니다
          </FallInPlace>
        }
        description={
          <FallInPlace
            delay={0.4}
            fontWeight="medium"
            textAlign="center"
            color="gray.600"
            _dark={{ color: "gray.400" }}
            fontSize={{ base: "md", md: "xl", lg: "2xl" }}
            initialInView
            pt="12"
            pb="12"
          >
            미국의 소스코드를 분석하여 모방하여 의존성을 제거하여 공유하기 위해
            노력합니다.
            <Br display={{ base: "none", md: "inline" }} /> Operate and manage
            여러 작은 실험을 통해 확장해나가려고 합니다.{" "}
            <Br display={{ base: "none", md: "inline" }} /> View analytics and
            피드백과 많은 참여 부탁드립니다.
          </FallInPlace>
        }
      ></Hero>

      <Hero
        as={Stack}
        id="home"
        alignItems="center"
        textAlign="center"
        description={
          <FallInPlace
            delay={0.4}
            fontWeight="medium"
            textAlign="center"
            color="gray.600"
            _dark={{ color: "gray.400" }}
            fontSize={{ base: "md", md: "xl", lg: "2xl" }}
            initialInView
            pt="12"
            pb="12"
          >
            현재 개발 중 좋은 아이디어 있으면 알려주세요
          </FallInPlace>
        }
      ></Hero>
    </>
  );
}
